# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60fb61cdfad74e2080937407c6543491c70a980f4bf5a89c548a014d89763c4f8ea50c41fdd119f498878f1c3340cb9ccaf64631fcc607287b606dbbcecd42ee

test:
  secret_key_base: dab27f0a7993d018cbfa9588ee54b807de5b61bb766bb1b426276f92be9fbf8af55f27fde5f03b3fbe2a53ba3c351844f1498754b907e062e26df076d41dc088

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
